version: "3.2"

services:

  powerlyra-worker:
    image: 127.0.0.1:5000/powerlyra
    volumes:
      - datasets:/sgp/datasets/
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == worker
    networks:
      mpinetwork:
        aliases:
          - '{{.Service.Name}}-{{.Task.Slot}}'
  powerlyra-master:
    image: 127.0.0.1:5000/powerlyra
    volumes:
      - datasets:/sgp/datasets/
      - results:/sgp/results/
      - parameters:/sgp/parameters/
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    networks:
      - mpinetwork

networks:
  mpinetwork:
    driver: overlay

volumes:
  datasets:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/apacaci/datasets"
  results:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/apacaci/sgp-framework/pl-cluster-results"
  parameters:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/apacaci/sgp-framework/streaming-graph-partitioning/containers/analytics/parameters"
